# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

google_maps_api: AIzaSyBROsr7gvXULBlTlczFNWteUwM6LZhvnCI
admin_email: deanacmslater@gmail.com
admin_crypted_password: $2a$10$uk.zLWY7b6HWS0zrhOdasuSYgIKcsrWFjeYL5VpoOZoA5RrW3jtA6

# devise:
#     registrations:
#       admin:
#         signed_up_but_not_approved: 'You have signed up successfully but your account has not been approved by your administrator yet'
#     failure:
#       not_approved: 'Your account has not been approved by your administrator yet.'