# Add configuration values here, as shown below.
#

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

google_maps_api: AIzaSyBqMD4oWC4W4sbK9nyG47rvkWYRABZ0WlY
